export {
  PRODUCT_APP_ID as DESKTOP_APP_ID,
  PRODUCT_CHROMIUM_PARTITION,
  PRODUCT_CONFIG_DIRECTORY_NAME as DESKTOP_USER_DATA_DIRECTORY_NAME,
  PRODUCT_DEV_APP_ID as DESKTOP_DEV_APP_ID,
  PRODUCT_DISPLAY_NAME as DESKTOP_APP_NAME,
  PRODUCT_NAMESPACE,
  productUserModelId as desktopAppUserModelId,
} from "../../platform/product-identity.js";
