<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <BaseIntermediateOutputPath>generated\sdk-restore\</BaseIntermediateOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3537.50" PrivateAssets="all" />
  </ItemGroup>
</Project>
