import { isDeepStrictEqual } from "node:util";
import type { ConfirmationRequest } from "../confirmation/contracts.js";
import type { ModelInputAttachmentRef } from "../model-input/index.js";
import type { ToolFactValue } from "./fact-value.js";
import type { ToolJsonSchema, ToolJsonSchemaValue } from "./schema.js";

export type ToolInputSchema = {
  readonly type: "object";
  readonly properties: Record<string, ToolJsonSchemaValue>;
  readonly required?: readonly string[];
  readonly additionalProperties?: boolean | ToolJsonSchema;
  /** Preserve JSON Schema keywords not interpreted by the host. */
  readonly [keyword: string]: unknown;
};

export type ToolCategory = "research" | "workspace" | "filesystem" | "terminal" | "web" | "mcp" | "other";

export type ToolRiskLevel = "low" | "medium" | "high";

export type ToolOperationType =
  | "read-only"
  | "read-write"
  | "execute"
  | "external-submit";

export type ToolFileDisplayOperation =
  | "create"
  | "write"
  | "append"
  | "edit"
  | "delete";

export type ToolErrorDomain =
  | "tool_error"
  | "runtime_error"
  | "model_error"
  | "ui_submit_error"
  | "process_error";

export type ToolErrorFactValue =
  | string
  | number
  | boolean
  | null
  | readonly ToolErrorFactValue[]
  | { readonly [key: string]: ToolErrorFactValue };

export type ToolErrorFacts = Readonly<Record<string, ToolErrorFactValue>>;

/** The proven phase that produced a failed ToolCallResult. */
export type ToolFailureAttribution = "schema_validation" | "execution_failure";

export type ToolRuntimeHint =
  | {
      readonly kind: "command_shell";
      readonly shellId: string;
      readonly label: string;
      readonly executable: string;
      readonly syntax: "cmd" | "powershell" | "posix";
      readonly platform: NodeJS.Platform;
      readonly invocation: readonly string[];
      readonly commandLineParameter: string;
      readonly notes: readonly string[];
    }
  | {
      readonly kind: "mcp_tool";
      readonly serverId: string;
      readonly protocolName: string;
      readonly readOnlyHint?: boolean;
      readonly destructiveHint?: boolean;
      readonly idempotentHint?: boolean;
      readonly openWorldHint?: boolean;
    };

/**
 * 工具的「能力契约元数据」（FR-TOOL-002）。
 *
 * 这是「工具是否需要确认 / 是否只读 / 可否并行 / 是否具备删除子能力」等能力判定的
 * **唯一依据**。能力判定必须基于这些显式契约字段，而非工具名正则、关键字或硬编码白名单。
 *
 * 对模型可见的工具，`validateModelVisibleToolContract` 只把 `category` / `riskLevel` /
 * `operationType` / `requiresConfirmation` 以及可选的 `fileOperation` 作为执行/副作用事实校验。
 * 预览长度、折叠和用户可见文案属于 Panel/read-model，不进入工具执行契约。
 *
 * 确认策略保守默认：当 `requiresConfirmation` 缺失（例如经松散运行时数据绕过完备门槛的
 * 兼容/MCP 路径）时，`resolveEffectiveConfirmationRequirement` 对高影响动作
 * （execute / external-submit / delete / high risk）默认按需确认，确保不会因契约字段缺失
 * 而静默执行高影响动作。
 */
export type ToolDefinitionMetadata = {
  /** 工具类别，用于归类与可见性 scope 派生。 */
  readonly category: ToolCategory;
  /** 风险等级，能力判定（如默认确认策略）的依据之一。 */
  readonly riskLevel: ToolRiskLevel;
  /** 粗粒度读写执行分类；并行许可以 `operationType === "read-only"` 全员只读为前提。 */
  readonly operationType: ToolOperationType;
  /** 显式确认策略：是否需要逐条确认。能力判定唯一依据，缺失时走保守默认。 */
  readonly requiresConfirmation: boolean;
  readonly runtimeHints?: readonly ToolRuntimeHint[];
  /**
   * 文件系统操作工具显式声明的文件操作子类型（create/write/append/edit/delete）。
   *
   * 这是工具自身声明的显式能力契约，用于工作区能力判定（例如是否具备删除能力），
   * 取代按工具名正则猜测。只有真正执行文件操作的 builtin 工具才声明该字段；
   * 非文件工具（搜索、命令、HTTP、MCP 等）不声明，判定时按 undefined 处理。
   *
   * 注意：`operationType` 是粗粒度读写执行分类，无法区分“删除”这类子能力；
   * 删除工具的 `operationType` 仍是 "read-write"（删除属于写操作），删除子能力由本字段表达。
   */
  readonly fileOperation?: ToolFileDisplayOperation;
};

export type ToolContinuation = {
  readonly ref?: string;
  readonly nextInput?: ToolFactValue;
  readonly note?: string;
};

export type ToolResultError = {
  readonly message: string;
  readonly domain?: ToolErrorDomain;
  readonly facts?: ToolErrorFacts;
  readonly retryable?: boolean;
};

export type ToolResult = {
  readonly body:
    | { readonly format: "none" }
    | { readonly format: "text"; readonly text: string }
    | { readonly format: "json"; readonly value: ToolFactValue };
  readonly error?: ToolResultError;
};

export type ToolDefinition = {
  readonly name: string;
  readonly description: string;
  readonly inputSchema: ToolInputSchema;
  /** Optional provider/MCP output contract, retained without forcing validation. */
  readonly outputSchema?: ToolJsonSchema;
  readonly metadata?: ToolDefinitionMetadata;
};

export type ToolCallRequest = {
  /**
   * Provider/protocol call id. It must be returned unchanged to the originating model.
   * ProviderCallId is not guaranteed to be unique across the whole product Run and
   * never replaces the internal invocation identity.
   */
  readonly providerCallId: string;
  /**
   * Authoritative Synech invocation identity. Generated by Ordinary when the
   * call is accepted, stable for retry/UI reconnect, and never derived from the
   * provider id. Always present on every accepted tool call.
   */
  readonly invocationId: string;
  /** Invocation identity of the parent tool call, when this is a nested delegation. */
  readonly parentInvocationId?: string;
  readonly toolName: string;
  readonly input: ToolFactValue | undefined;
};

/**
 * Provider-side tool call as the model emits it: the external call id from the
 * model protocol, the tool name, and the raw input. No Synech-owned identity
 * is attached at this layer. The owning feature (Ordinary) mints the
 * `invocationId` when it accepts the call.
 *
 * `parentInvocationId` is set by the delegated AgentTool loop when the call is
 * nested under a delegated AgentTool invocation. It is an execution-context
 * field, not a model-bound identity, so it stays on this binding-side type.
 */
export type ProviderToolCall = {
  readonly providerCallId: string;
  readonly toolName: string;
  readonly input: ToolFactValue | undefined;
  /** Set on a tool call nested inside a delegated AgentTool invocation. */
  readonly parentInvocationId?: string;
  /**
   * Per-message token from the model loop (typically the durable Session entry
   * id of the assistant message). Mixed into the Synech invocation identity so
   * the same provider call id reused across different model rounds inside one
   * run does not collide.
   */
  readonly roundId: string;
};

/**
 * Tool call bound to a Synech invocation. Same shape as `ProviderToolCall`
 * with the addition of the Synech-owned `invocationId`. Carried through
 * Ordinary and the tool runtime, never on the model boundary.
 */
export type AcceptedToolInvocation = ProviderToolCall & {
  readonly invocationId: string;
};

/**
 * Measurement facts for one AgentTool delegation. The parent run remains the
 * owner of the tool result; this records only the child work it delegated.
 */
export type DelegatedAgentExecutionMetadata = {
  readonly modelRounds: number;
  readonly toolCallCount: number;
  readonly usage: DelegatedAgentUsage;
};

/** Usage attributable to one delegated AgentTool invocation, independent of a model adapter. */
export type DelegatedAgentUsage = {
  readonly requestCount?: number;
  readonly inputTokens?: number;
  readonly outputTokens?: number;
  readonly totalTokens?: number;
  readonly cachedInputTokens?: number;
  readonly cacheWriteInputTokens?: number;
  readonly uncachedInputTokens?: number;
  readonly reasoningOutputTokens?: number;
  readonly estimatedCostUsd?: number;
};

export type ToolCallResult = {
  /** Provider/protocol call id. It must be returned unchanged to the originating model. */
  readonly providerCallId: string;
  /**
   * Authoritative Synech invocation identity. Generated by Ordinary when the
   * call is accepted; carried unchanged through execution and persistence.
   */
  readonly invocationId: string;
  /** Invocation identity of the parent tool call, when this is a nested delegation. */
  readonly parentInvocationId?: string;
  readonly toolName: string;
  readonly input: ToolFactValue | undefined;
  readonly output: ToolFactValue | undefined;
  /** JSON-safe identity retained across restart for Pi Session image reconciliation. */
  readonly modelAttachmentRefs?: readonly ModelInputAttachmentRef[];
  readonly status: "completed" | "failed" | "approval_required" | "cancelled";
  readonly error?: string;
  readonly errorDomain?: ToolErrorDomain;
  readonly errorFacts?: ToolErrorFacts;
  /** Present only when the runtime can prove the phase that produced this failure. */
  readonly failureAttribution?: ToolFailureAttribution;
  /** Present only for a completed, failed, or cancelled delegated AgentTool invocation. */
  readonly delegatedExecution?: DelegatedAgentExecutionMetadata;
  readonly durationMs: number;
  readonly confirmationRequest?: ConfirmationRequest;
};

/** Resolves the authoritative Synech invocation identity for any accepted tool call fact. */
export function toolInvocationId(value: Pick<ToolCallRequest, "invocationId">): string {
  return value.invocationId;
}

/**
 * Two tool call facts describe the same invocation when they share the
 * authoritative `invocationId`. Provider call id, name, input, and parent
 * identity are not part of the identity decision.
 */
export function sameInvocationIdentity(
  left: Pick<ToolCallRequest, "invocationId">,
  right: Pick<ToolCallRequest, "invocationId">,
): boolean {
  return left.invocationId === right.invocationId;
}

/**
 * Two tool call facts describe the same definition when they agree on the
 * provider call id, tool name, input, and parent invocation identity.
 * Useful when the model adapter re-emits the assistant message and Ordinary
 * needs to confirm it is the same logical call before re-binding.
 */
export function sameInvocationDefinition(
  left: Pick<ToolCallRequest, "providerCallId" | "toolName" | "input" | "parentInvocationId">,
  right: Pick<ToolCallRequest, "providerCallId" | "toolName" | "input" | "parentInvocationId">,
): boolean {
  return left.providerCallId === right.providerCallId
    && left.toolName === right.toolName
    && left.parentInvocationId === right.parentInvocationId
    && sameToolInput(left.input, right.input);
}

/**
 * Two tool result facts describe the same result identity when they share the
 * `invocationId`. Status, output, error, and runtime metadata are excluded.
 */
export function sameToolResultIdentity(
  left: Pick<ToolCallResult, "invocationId">,
  right: Pick<ToolCallResult, "invocationId">,
): boolean {
  return left.invocationId === right.invocationId;
}

/**
 * Two tool result facts describe the same content when their business-meaning
 * fields match. Runtime fields (durationMs, timing, transport-only envelopes)
 * and identity fields (invocationId, providerCallId) are excluded; UI fields
 * (display, summary) are excluded by the fact that result content does not
 * carry them.
 */
export function sameToolResultContent(
  left: Pick<ToolCallResult, "status" | "output" | "error" | "errorDomain" | "errorFacts" | "failureAttribution" | "modelAttachmentRefs" | "delegatedExecution" | "parentInvocationId">,
  right: Pick<ToolCallResult, "status" | "output" | "error" | "errorDomain" | "errorFacts" | "failureAttribution" | "modelAttachmentRefs" | "delegatedExecution" | "parentInvocationId">,
): boolean {
  return left.status === right.status
    && sameToolInput(left.output, right.output)
    && left.error === right.error
    && left.errorDomain === right.errorDomain
    && sameErrorFacts(left.errorFacts, right.errorFacts)
    && left.failureAttribution === right.failureAttribution
    && left.parentInvocationId === right.parentInvocationId
    && sameAttachmentRefs(left.modelAttachmentRefs, right.modelAttachmentRefs)
    && sameDelegatedExecution(left.delegatedExecution, right.delegatedExecution);
}

/**
 * Idempotency comparison for a tool result re-delivery. Returns true only when
 * the two results agree on the authoritative invocation, the call definition
 * (toolName, input, parentInvocationId), the approval request (if any), and
 * the business-meaning result content. Used to decide whether an incoming
 * re-delivery of the same invocation can be silently dropped; a different
 * `toolName` or `input` for the same `invocationId` is treated as a real
 * conflict, not an idempotent match, so a stale approval cannot survive a
 * call-definition change.
 */
export function sameResultForIdempotency(
  left: ToolCallResult,
  right: ToolCallResult,
): boolean {
  if (!sameToolResultIdentity(left, right)) return false;
  if (left.toolName !== right.toolName) return false;
  if (left.parentInvocationId !== right.parentInvocationId) return false;
  if (!sameToolInput(left.input, right.input)) return false;
  return sameConfirmationRequestShape(left.confirmationRequest, right.confirmationRequest)
    && sameToolResultContent(left, right);
}

function sameConfirmationRequestShape(
  left: ConfirmationRequest | undefined,
  right: ConfirmationRequest | undefined,
): boolean {
  if (left === right) return true;
  if (left === undefined || right === undefined) return false;
  return left.confirmationId === right.confirmationId
    && left.invocationId === right.invocationId
    && left.title === right.title
    && left.actionSummary === right.actionSummary
    && left.consequence === right.consequence
    && left.riskLevel === right.riskLevel
    && left.requestedAt === right.requestedAt
    && left.expiresAt === right.expiresAt
    && left.resumeAvailability === right.resumeAvailability
    && sameStringList(left.affectedResources, right.affectedResources)
    && sameStringList(left.sourceRefs, right.sourceRefs)
    && left.conversationId === right.conversationId;
}

function sameStringList(left: readonly string[], right: readonly string[]): boolean {
  if (left === right) return true;
  if (left.length !== right.length) return false;
  for (let index = 0; index < left.length; index += 1) {
    if (left[index] !== right[index]) return false;
  }
  return true;
}

function sameToolInput(
  left: ToolFactValue | undefined,
  right: ToolFactValue | undefined,
): boolean {
  return isDeepStrictEqual(left, right);
}

function sameErrorFacts(
  left: ToolErrorFacts | undefined,
  right: ToolErrorFacts | undefined,
): boolean {
  return isDeepStrictEqual(left, right);
}

function sameAttachmentRefs(
  left: readonly ModelInputAttachmentRef[] | undefined,
  right: readonly ModelInputAttachmentRef[] | undefined,
): boolean {
  if (left === right) return true;
  if (left === undefined || right === undefined) return false;
  if (left.length !== right.length) return false;
  return left.every((item, index) => {
    const other = right[index];
    if (other === undefined) return false;
    return item.kind === other.kind
      && item.mimeType === other.mimeType
      && item.attachmentId === other.attachmentId
      && item.inputRef === other.inputRef
      && item.byteLength === other.byteLength
      && item.sha256 === other.sha256;
  });
}

function sameDelegatedExecution(
  left: DelegatedAgentExecutionMetadata | undefined,
  right: DelegatedAgentExecutionMetadata | undefined,
): boolean {
  if (left === right) return true;
  if (left === undefined || right === undefined) return false;
  return left.modelRounds === right.modelRounds
    && left.toolCallCount === right.toolCallCount
    && isDeepStrictEqual(left.usage, right.usage);
}

export type ToolSecurityDecision =
  | {
      readonly decision: "allow";
      readonly reason: string;
    }
  | {
      readonly decision: "approval_required";
      readonly reason: string;
      readonly title: string;
      readonly actionSummary: string;
      readonly consequence?: string;
      readonly affectedResources: readonly string[];
      readonly riskLevel: ToolRiskLevel;
      readonly sourceRefs: readonly string[];
    }
  | {
      readonly decision: "blocked";
      readonly reason: string;
      readonly code: string;
      readonly affectedResources: readonly string[];
      readonly sourceRefs: readonly string[];
    };

export type ToolSecurityEvaluationContext = {
  readonly platform: NodeJS.Platform;
  readonly approvedConfirmationIds?: readonly string[];
  readonly confirmationPolicy?: ToolConfirmationPolicy;
  readonly workspaceRoot?: string;
};

export interface ToolSecurityPolicy {
  evaluateToolCall(request: ToolCallRequest, definition: ToolDefinition, context: ToolSecurityEvaluationContext): ToolSecurityDecision;
}

/** Host-owned product scope carried through neutral tool execution facts. */
export type ToolExecutionResourceScope = {
  readonly ownerKind: string;
  readonly ownerId: string;
};

export type ToolExecutionContext = {
  readonly callerAgentId: string;
  readonly traceId: string;
  readonly goalId: string;
  readonly conversationId?: string;
  readonly resourceScope?: ToolExecutionResourceScope;
  /**
   * Synech invocation identity for the executing call. Adapters that need the
   * provider-side id (for example to map back to a Pi tool result entry) must
   * read it from the bound `ToolCallRequest.providerCallId`, not from this field.
   */
  readonly invocationId?: string;
  /** Provider-side call id, exposed only when an adapter truly needs it. */
  readonly providerCallId?: string;
  readonly approvedConfirmationIds?: readonly string[];
  readonly confirmationPolicy?: ToolConfirmationPolicy;
  readonly abortSignal?: AbortSignal;
  /** Live-only bounded execution evidence. Reporting must never change the tool outcome. */
  readonly reportProgress?: (progress: ToolExecutionProgress) => void;
};

export type ToolExecutionProgress =
  | {
      readonly kind: "command_output";
      readonly stdoutTail?: string;
      readonly stderrTail?: string;
      readonly stdoutChars: number;
      readonly stderrChars: number;
    }
  | {
      readonly kind: "mcp_progress";
      readonly progress?: number;
      readonly total?: number;
      readonly message?: string;
    };

export type ToolCallProgress = Pick<ToolCallRequest, "providerCallId" | "invocationId" | "toolName"> & {
  readonly progress: ToolExecutionProgress;
};

export type ToolPermissionCheck = {
  readonly callerAgentId: string;
  readonly allowedTools: readonly string[];
  readonly approvedConfirmationIds?: readonly string[];
  readonly confirmationPolicy?: ToolConfirmationPolicy;
};

export type ToolConfirmationPolicy = "prompt" | "full_access";

export type SandboxOperation =
  | "read"
  | "list"
  | "search"
  | "write"
  | "edit"
  | "delete"
  | "execute";

export type SandboxPolicyRequest = {
  readonly operation: SandboxOperation;
  readonly workspaceRoot: string;
  readonly relativePath?: string;
  readonly bytes?: number;
  readonly command?: string;
  readonly commandLine?: string;
  readonly args?: readonly string[];
};

export type SandboxPolicyDecision =
  | {
      readonly allowed: true;
    }
  | {
      readonly allowed: false;
      readonly code: string;
      readonly reason: string;
    };

export interface SandboxPolicy {
  check(request: SandboxPolicyRequest): SandboxPolicyDecision;
}

export interface ToolExecutor {
  readonly definition: ToolDefinition;
  execute(input: unknown, context: ToolExecutionContext): Promise<unknown | ToolExecutorResult>;
}

export type ToolExecutorResult = {
  readonly kind: "tool_call_result";
  readonly result: ToolCallResult;
};

export interface ToolExecutionBroker {
  list(): ToolDefinition[];
  has(name: string): boolean;
  execute(
    request: ToolCallRequest,
    context: ToolExecutionContext,
    permission: ToolPermissionCheck
  ): Promise<ToolCallResult>;
  register?(executor: ToolExecutor): void;
}

/**
 * A side-effect-free decision about whether one exact tool call may enter its executor.
 * `ready.request` is the detached, JSON-safe fact that a later execution will use.
 */
export type ToolExecutionPreflight =
  | {
      readonly status: "ready";
      readonly request: ToolCallRequest;
    }
  | {
      readonly status: "approval_required";
      readonly result: ToolCallResult & { readonly status: "approval_required" };
    }
  | {
      readonly status: "blocked";
      readonly result: ToolCallResult & { readonly status: "failed" | "cancelled" };
    };

/**
 * Production tool gateways expose the same authorization boundary independently from
 * execution so an outer runtime can pause before invoking a side-effecting executor.
 */
export interface ToolExecutionGateway extends ToolExecutionBroker {
  preflight(
    request: ToolCallRequest,
    context: ToolExecutionContext,
    permission: ToolPermissionCheck
  ): ToolExecutionPreflight;
  /** Applies the same model-delivery envelope to a tool-like fact produced outside a registered executor. */
  deliverResult?(
    result: ToolCallResult,
    permission: ToolPermissionCheck,
    ownerId: string,
  ): Promise<ToolCallResult>;
}
